# -*- coding: utf-8 -*-
from .base import *

"""
Django settings for airline project.

Generated by 'django-admin startproject' using Django 2.0.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
import dj_database_url

DEBUG = True
ALLOWED_HOSTS = ['127.0.0.1', 'django-airlines.heroku.com']

# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': get_env_variable('DB_NAME'),
        'USER': get_env_variable('DB_USER'),
        'PASSWORD': get_env_variable('DB_PSWD'),
    }
}

# DB_URL = get_env_variable('DATABASE_URL')
db_from_env = dj_database_url.config()
DATABASES['default'].update(db_from_env)